// stubs/react/js/Pages/Profile/Partials/DeleteUserForm.jsx
import { useRef, useState } from 'react'
import { useForm } from '@inertiajs/inertia-react'
import Label from '@/Components/Label'
import Input from '@/Components/Input'
import InputError from '@/Components/InputError'
import Modal from '@/Components/Modal'
import Button from '@/Components/Button'

export default function DeleteUserForm({ className }) {
    const [confirmingUserDeletion, setConfirmingUserDeletion] = useState(false)
    const passwordInput = useRef()

    const {
        data,
        setData,
        delete: destroy,
        processing,
        reset,
        errors,
    } = useForm({
        password: '',
    })

    const confirmUserDeletion = () => {
        setConfirmingUserDeletion(true)
    }

    const deleteUser = (e) => {
        e.preventDefault()

        destroy(route('profile.destroy'), {
            preserveScroll: true,
            onSuccess: () => closeModal(),
            onError: () => passwordInput.current.focus(),
            onFinish: () => reset(),
        })
    }

    const closeModal = () => {
        setConfirmingUserDeletion(false)

        reset()
    }

    return (
        <section className={`space-y-6 ${className}`}>
            <header>
                <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                    Delete Account
                </h2>

                <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                    Once your account is deleted, all of its resources and data
                    will be permanently deleted. Before deleting your account,
                    please download any data or information that you wish to
                    retain.
                </p>
            </header>

            <Button variant="danger" onClick={confirmUserDeletion}>
                Delete Account
            </Button>

            <Modal show={confirmingUserDeletion} onClose={closeModal}>
                <form onSubmit={deleteUser} className="p-6">
                    <h2 className="text-lg font-medium text-gray-900 dark:text-gray-100">
                        Are you sure you want to delete your account?
                    </h2>

                    <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">
                        Once your account is deleted, all of its resources and
                        data will be permanently deleted. Please enter your
                        password to confirm you would like to permanently delete
                        your account.
                    </p>

                    <div className="mt-6">
                        <Label
                            for="password"
                            value="Password"
                            className="sr-only"
                        />

                        <Input
                            id="password"
                            type="password"
                            name="password"
                            ref={passwordInput}
                            value={data.password}
                            handleChange={(e) =>
                                setData('password', e.target.value)
                            }
                            className="mt-1 block w-3/4"
                            isFocused
                            placeholder="Password"
                        />

                        <InputError
                            message={errors.password}
                            className="mt-2"
                        />
                    </div>

                    <div className="mt-6 flex justify-end">
                        <Button variant="secondary" onClick={closeModal}>
                            Cancel
                        </Button>

                        <Button variant="danger" className="ml-3" processing={processing}>
                            Delete Account
                        </Button>
                    </div>
                </form>
            </Modal>
        </section>
    )
}

// stubs/vue/js/jsx/Pages/Profile/Partials/DeleteUserForm.jsx
import { defineComponent, nextTick, ref, withKeys } from 'vue'
import { useForm } from '@inertiajs/inertia-vue3'
import Label from '@/Components/Label'
import Input from '@/Components/Input'
import InputError from '@/Components/InputError'
import Modal from '@/Components/Modal'
import Button from '@/Components/Button'

export default defineComponent({
    setup() {
        const confirmingUserDeletion = ref(false)
        const passwordInput = ref(null)

        const form = useForm({
            password: '',
        })

        const confirmUserDeletion = () => {
            confirmingUserDeletion.value = true

            nextTick(() => passwordInput.value?.$el.focus())
        }

        const deleteUser = () => {
            form.delete(route('profile.destroy'), {
                preserveScroll: true,
                onSuccess: () => closeModal(),
                onError: () => passwordInput.value?.$el.focus(),
                onFinish: () => form.reset(),
            })
        }

        const closeModal = () => {
            confirmingUserDeletion.value = false

            form.reset()
        }

        return () => (
            <section class="space-y-6">
                <header>
                    <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
                        Delete Account
                    </h2>

                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                        Once your account is deleted, all of its resources and
                        data will be permanently deleted. Before deleting your
                        account, please download any data or information that
                        you wish to retain.
                    </p>
                </header>

                <Button
                    variant="danger"
                    onClick={() => {
                        confirmUserDeletion()
                    }}
                >
                    Delete Account
                </Button>

                <Modal
                    show={confirmingUserDeletion.value}
                    onClose={() => {
                        closeModal()
                    }}
                >
                    <div class="p-6">
                        <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
                            Are you sure you want to delete your account?
                        </h2>

                        <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                            Once your account is deleted, all of its resources
                            and data will be permanently deleted. Please enter
                            your password to confirm you would like to
                            permanently delete your account.
                        </p>

                        <div class="mt-6 space-y-2">
                            <Label
                                for="password"
                                value="Password"
                                class="sr-only"
                            />

                            <Input
                                id="password"
                                ref={passwordInput}
                                v-model={form.password}
                                type="password"
                                class="block w-3/4"
                                placeholder="Password"
                                onKeyup={withKeys(deleteUser, ['enter'])}
                            />

                            <InputError
                                message={form.errors.password}
                            />
                        </div>

                        <div class="mt-6 flex justify-end gap-3">
                            <Button
                                variant="secondary"
                                onClick={() => {
                                    closeModal()
                                }}
                            >
                                Cancel
                            </Button>

                            <Button
                                variant="danger"
                                disabled={form.processing}
                                onClick={() => {
                                    deleteUser()
                                }}
                            >
                                Delete Account
                            </Button>
                        </div>
                    </div>
                </Modal>
            </section>
        )
    },
})
