// stubs/react/js/Components/PerfectScrollbar.jsx
import PerfectScrollbar from "perfect-scrollbar";
import { useEffect, useRef } from "react";

export default (props) => {
    const { tag: Tag = "div" } = props;

    const el = useRef(null);

    let ps = null;

    const update = () => {
        if (ps) {
            ps.update();
        }
    };

    useEffect(() => {
        ps = new PerfectScrollbar("#a", props.settings || {});

        return () => {
            ps.destroy();
        };
    }, []);

    return (
        <Tag
            className={`relative ${props.className}`}
            onMouseOver={update}
            ref={el}
            id="a"
        >
            {props.children}
        </Tag>
    );
};

// stubs/vue/js/Components/PerfectScrollbar.jsx
import {
    defineComponent,
    onMounted,
    onUnmounted,
    ref,
    withModifiers,
} from 'vue'
import PerfectScrollbar from 'perfect-scrollbar'

export default defineComponent({
    props: {
        settings: {
            type: Object,
            default: {},
        },
        tagname: {
            type: String,
            default: 'div',
        },
    },

    setup(props, { slots }) {
        const { settings, tagname: Tag } = props

        let ps = null

        const update = () => {
            if (ps) {
                ps.update()
            }
        }

        const el = ref(null)

        onMounted(() => {
            ps = new PerfectScrollbar(el.value, settings)
        })

        onUnmounted(() => {
            ps.destroy()
        })

        return () => (
            <Tag
                ref={el}
                class="relative"
                onmouseover={withModifiers(update, ['once'])}
            >
                {slots.default?.()}
            </Tag>
        )
    },
})
