// stubs/react/js/Components/PerfectScrollbar.jsx
import PerfectScrollbar from "perfect-scrollbar";
import { useEffect, useRef } from "react";

export default (props) => {
    const { tag: Tag = "div" } = props;

    const el = useRef(null);

    let ps = null;

    const update = () => {
        if (ps) {
            ps.update();
        }
    };

    useEffect(() => {
        ps = new PerfectScrollbar("#a", props.settings || {});

        return () => {
            ps.destroy();
        };
    }, []);

    return (
        <Tag
            className={`relative ${props.className}`}
            onMouseOver={update}
            ref={el}
            id="a"
        >
            {props.children}
        </Tag>
    );
};

// stubs/vue/js/Components/PerfectScrollbar.vue
<template>
    <component :is="tagname" ref="el" @mouseover.once="update">
        <slot />
    </component>
</template>

<script>
import { onMounted, onUnmounted, ref } from 'vue'
import PerfectScrollbar from 'perfect-scrollbar'

export default {
    props: {
        settings: {
            type: Object,
            default: {},
        },
        tagname: {
            type: String,
            default: 'div',
        },
    },
    setup(props) {
        const { settings, tagname } = props

        let ps = null

        const update = () => {
            if (ps) {
                ps.update()
            }
        }

        const el = ref(null)

        onMounted(() => {
            ps = new PerfectScrollbar(el.value, settings)
        })

        onUnmounted(() => {
            ps.destroy()
        })

        return {
            el,
            update,
        }
    },
}
</script>
