// stubs/vue/js/sfc/Components/ValidationErrors.vue
<script setup>
import { computed } from 'vue'
import { usePage } from '@inertiajs/vue3'

const errors = computed(() => usePage().props.errors)

const hasErrors = computed(() => Object.keys(errors.value).length > 0)
</script>

<template>
    <div v-if="hasErrors">
        <div class="font-medium text-red-600">
            Whoops! Something went wrong.
        </div>

        <ul class="mt-3 list-disc list-inside text-sm text-red-600">
            <li v-for="(error, key) in errors" :key="key">{{ error }}</li>
        </ul>
    </div>
</template>

// stubs/react/js/Components/ValidationErrors.jsx
export default ({ errors }) => {
    return (
        Object.keys(errors).length > 0 && (
            <div className="mb-4">
                <div className="font-medium text-red-600">
                    Whoops! Something went wrong.
                </div>

                <ul className="mt-3 text-sm text-red-600 list-disc list-inside">
                    {Object.keys(errors).map(function (key, index) {
                        return <li key={index}>{errors[key]}</li>
                    })}
                </ul>
            </div>
        )
    )
}
