// stubs/react/js/Components/ValidationErrors.jsx
export default ({ errors }) => {
    return (
        Object.keys(errors).length > 0 && (
            <div className="mb-4">
                <div className="font-medium text-red-600">
                    Whoops! Something went wrong.
                </div>

                <ul className="mt-3 text-sm text-red-600 list-disc list-inside">
                    {Object.keys(errors).map(function (key, index) {
                        return <li key={index}>{errors[key]}</li>
                    })}
                </ul>
            </div>
        )
    )
}

// stubs/vue/js/jsx/Components/ValidationErrors.jsx
import { defineComponent, computed } from 'vue'
import { usePage } from '@inertiajs/vue3'

export default defineComponent({
    setup() {
        const errors = computed(() => usePage().props.value.errors)

        const hasErrors = computed(() => Object.keys(errors.value).length > 0)

        return () => (
            <div>
                {hasErrors.value && (
                    <>
                        <div class="font-medium text-red-600">
                            Whoops! Something went wrong.
                        </div>

                        <ul class="mt-3 list-disc list-inside text-sm text-red-600">
                            {Object.entries(errors.value).map(
                                ([key, error]) => (
                                    <li ley={key}>{error}</li>
                                )
                            )}
                        </ul>
                    </>
                )}
            </div>
        )
    },
})
