// stubs/react/js/Pages/Components/Buttons.jsx
import Button from '@/Components/Button'
import Authenticated from '@/Layouts/Authenticated'

export default (props) => {
    const variants = [
        'primary',
        'success',
        'danger',
        'warning',
        'info',
        'black',
        'white',
        'transparent',
    ]

    const sizes = ['sm', 'base', 'lg']

    return (
        <Authenticated
            title="Buttons"
            auth={props.auth}
            errors={props.errors}
            header={
                <h2 className="text-xl font-semibold">
                    Buttons
                </h2>
            }
        >
            <div className="p-6">
                <div className="grid items-center gap-6">
                    {variants.map((variant) => (
                        <div
                            key={variant}
                            className="grid items-start grid-cols-3 gap-6 justify-items-center"
                        >
                            {sizes.map((size) => (
                                <Button
                                    key={size}
                                    type="button"
                                    variant={variant}
                                    size={size}
                                    className="capitalize"
                                >
                                    {variant}
                                </Button>
                            ))}
                        </div>
                    ))}
                </div>
            </div>

            <div className="p-6">
                <div className="grid items-center gap-6">
                    {variants.map((variant) => (
                        <div
                            key={variant}
                            className="grid items-start grid-cols-3 gap-6 justify-items-center"
                        >
                            {sizes.map((size) => (
                                <Button
                                    key={size}
                                    type="button"
                                    variant={variant}
                                    size={size}
                                    startIcon="tabler--home"
                                    text={variant}
                                    className="capitalize"
                                />
                            ))}
                        </div>
                    ))}
                </div>
            </div>

            <div className="p-6">
                <div className="grid items-center gap-6">
                    {variants.map((variant) => (
                        <div
                            key={variant}
                            className="grid items-start grid-cols-3 gap-6 justify-items-center"
                        >
                            {sizes.map((size) => (
                                <Button
                                    key={size}
                                    variant={variant}
                                    size={size}
                                    icon="tabler--home"
                                    srText={variant}
                                />
                            ))}
                        </div>
                    ))}
                </div>
            </div>
        </Authenticated>
    )
}

// stubs/vue/js/Pages/Components/Buttons.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/Authenticated'
import Button from '@/Components/Button'

let buttonVariants = [
    "primary",
    "success",
    "danger",
    "warning",
    "info",
    "white",
    "black",
    "transparent",
];

let buttonSizes = ["sm", "base", "lg"]
</script>

<template>
    <AuthenticatedLayout title="Buttons">
        <template #header>
            <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <h2 class="text-xl font-semibold leading-tight">Buttons</h2>

                <Button
                    external
                    variant="black"
                    target="_blank"
                    class="max-w-xs"
                    href="https://github.com/kamona-wd/kui-laravel-breeze"
                    start-icon="tabler--brand-github"
                    text="Star on Github"
                />
            </div>
        </template>

        <div class="grid items-center gap-6 mt-4">
            <div v-for="variant in buttonVariants" :key="variant" class="grid items-start grid-cols-3 gap-4 justify-items-center">
                <Button 
                    v-for="size in buttonSizes" 
                    :key="size" 
                    :variant="variant" 
                    :size="size"
                    text="Button"
                />
            </div>

            <div v-for="variant in buttonVariants" :key="variant" class="grid items-start grid-cols-3 gap-4 justify-items-center">
                <Button 
                    v-for="size in buttonSizes" 
                    :key="size" 
                    :variant="variant" 
                    :size="size"
                    icon="tabler--home" 
                    sr-text="Icon only button"
                />
            </div>

            <div v-for="variant in buttonVariants" :key="variant" class="grid items-start grid-cols-3 gap-4 justify-items-center">
                <Button 
                    v-for="size in buttonSizes" 
                    :key="size" 
                    :variant="variant" 
                    :size="size"
                    start-icon="tabler--circle" 
                    text="Button"
                />
            </div>
        </div>
    </AuthenticatedLayout>
</template>
